### PR TITLE
issue/232-adding-support-for-prettier-2.x - Adding support for prettier 2x

### LINKED ISSUE #232: Add support for `prettier 2.x`
This issue was track work to ensure `vim-prettier` plays nicely with `prettier` 2.x

Will update the description of this issue in the next few days when I get a better idea on the scope

*** 

Did some preliminary work on local branch and will add some tasks that need to be done in order to address this issue:

- [ ] Update `vim-prettier` defaults to match `prettier 2.x` and move existing defaults to `classic` preset
- [ ] Ensure backwards compatibility with `prettier 1.x` 
- [ ] Create a "Classic" preset to still enable support for folks that cannot upgrade to prettier 2.0
- [ ] Ensure all existing supported plugins are working with `prettier 2.x`
- [ ] Update README to guide users on how to default to old `classic` preset

### PR DESCRIPTION
**Pull request by mitermayer**
Adding support for prettier 2.x

- Updates prettier default configuration
- Include "classic" preset for older configurations
- Bump package.json and yarn.lock dependencies
- Include missing configuration
- Bump prettier plugin dependencies 

***

Fixes: https://github.com/prettier/vim-prettier/issues/232

### CODE REVIEW

**Comment by mikabytes** [comment]
I can confirm this PR is solving all issues I reported in #232 

Thanks @mitermayer

**Comment by mitermayer** [comment]
I need to fix the builds and update docs then will merge this

**Comment by rockerBOO** [comment]
This seems to be blocking on the docker image. 

Alpine 3.8 has nodejs version 8.x. New prettier requires nodejs version 10.x. 

Alpine 3.9 ups the nodejs version to 10.x 
https://alpinelinux.org/posts/Alpine-3.9.0-released.html

Update [Dockerfile](https://github.com/prettier/vim-prettier/blob/master/Dockerfile#L1) to use Alpine 3.9.

--- 

Currently prettier  1.x doesn't support typescript type import hinting and won't run.

```
import type { MyType } from './types;
```
So getting this updated would be great. 

If you **need** to run prettier on these files currently, you can get away with updating your plugin to use the Prettier 2.0 version with maybe limited/broken support.

**Comment by mitermayer** [comment]
Sorry, Been struggling to get time to work in this with covid world. I will do my best to finalize this PR this week and do a new release. Apologies in advance

**Pull request merged**
