### PR TITLE
fix: always pass a string to executable(...)

### LINKED ISSUE #276: Error on NeoVim nightly
**Do you want to request a *feature* or report a *bug*?**

*bug*

**What is the current/expected behavior?**

Running :Prettier prints the following error message:
```
Error detected while processing function prettier#Prettier[1]..prettier#resolver#executable#getPath:
line    7:
E928: String required
```

However, I do have prettier installed:

```
:!which prettier
/home/jonathan/.config/nvm/12.18.3/bin/prettier

Press ENTER or type command to continue
```

**What version of `vim-prettier` are you using - (output of `:PrettierVersion`) ?**

1.0.0-beta

**What version of `prettier` are you using - (output of  `:PrettierCliVersion`) ?**

Running :PrettierCliVersion prints the following error message:
```
Error detected while processing function prettier#Prettier[1]..prettier#resolver#executable#getPath:
line    7:
E928: String required
```

**What is your `prettier` executable path - (output of  `:PrettierCliPath`) ?**

```
Error detected while processing function prettier#Prettier[1]..prettier#resolver#executable#getPath:
line    7:
E928: String required
```

**Did this work in previous versions of vim-prettier and/or prettier ?**

This works in stable neovim perfectly!

### PR DESCRIPTION
**Pull request by jrop**
**Summary**

Fixes #276 

**Test Plan**

I tested on NeoVim Nightly, and it works.  Still have to test in NeoVim 0.4, and Vim8.

### CODE REVIEW

**Comment by jrop** [comment]
It looks like #274 is very similar in objective.

**Comment by mitermayer** [comment]
@jrop with #274  being merged does this PR still applicable ?

**Comment by jrop** [comment]
@mitermayer #274 seems to be sufficient on its own.

**Comment by zeekhuge** [comment]
Hi @jrop 
Although I see that changes from #274 are present in my `vim-prettier`, I am still facing the same issue.
However, when I added changes suggested by you, the issue was fixed. 
Am I missing something ?

**Comment by jrop** [comment]
@zeekhuge I'm not sure TBH. It's been so long since I looked into this, I've lost pretty much all context.

**Pull request closed without merging**
