### PR TITLE
Making sure we can still save the results of last prettier async run on

### PR DESCRIPTION
**Pull request by mitermayer**
This is another follow up fix for https://github.com/prettier/vim-prettier/issues/62, enables user to still have their buffer formatted event when switching to other files faster than the async result is returned.

cc @alanhamlett

### CODE REVIEW

**Comment by alanhamlett** [comment]
Getting this error after updating vim-prettier:

```
Error detected while processing function <lambda>2[1]..<SNR>122_Prettier_Job_Close:
E118: Too many arguments for function: ch_status
E15: Invalid expression: ch_status(a:channel, {'part': 'out'}) == 'buffered'
```

**Comment by mitermayer** [comment]
Hi @alanhamlett,

Could you please provide me a bit more information so that I can start debugging it ?

1. What is your vim version ?
2. Can you supply vim-prettier version by the output of `:PrettierVersion`
3. What were the steps that you have done to generate that error ?

**Comment by alanhamlett** [comment]
1. Vim version: 8.0 with `exists('*setbufline') == 0`
2. Prettier version 0.2.2
3. Run command `:Prettier` to reproduce
4. OS X High Sierra

Vim doesn't have minor versions, but I can run any `has('patchx')` commands if that helps.

**Comment by mitermayer** [comment]
Hi @alanhamlett  thanks for that

Could you please provide me the steps you are doing so that i can try to reproduce this issue ?

Does it happen for all files ? Are you executing the prettier command manually ?

**Comment by alanhamlett** [comment]
After checking on another machine, it looks like a problem on my end. The machine with error was a fresh install of vim-prettier today so it probably would show that error before your fix too.

I'll debug it and let you know what's going on.

**Comment by alanhamlett** [comment]
My vim doesn't have `patch-8.0-0015`, which is when [support for options was added to ch_status](vim/vim/commit/7ef3810d28b7ab2edbfcafab3fe8ad8bc2c2f138). Could we remove `{'part': 'out'}` from [this line](https://github.com/prettier/vim-prettier/blob/46b496007760a1583a79bf7e5df2e825aa315884/autoload/prettier.vim#L128)?

**Comment by mitermayer** [comment]
Hi @alanhamlett,

Having a look on the vim commit that introduced this feature https://github.com/vim/vim/commit/7ef3810d28b7ab2edbfcafab3fe8ad8bc2c2f138, looks like it would involve a bit more than just removing that flag.

How hard would it be for you to upgrade your vim version ?

**Comment by mitermayer** [comment]
@alanhamlett  just added a fix for that by doing a new release of `vim-prettier` now on version 0.2.3

**Pull request merged**
