### PR TITLE
bugfix: fixing race condition incorrect buffer formating

### PR DESCRIPTION
**Pull request by mitermayer**
If user saved file and changed buffer too fast there was a chance that it could add the previous formatting to the next buffer when using vim 8 async job

Fixes: https://github.com/prettier/vim-prettier/issues/62

### CODE REVIEW

**Comment by alanhamlett** [comment]
Thanks! This causes prettier to not run on the saved file? Could we write back to the initial buffer instead of returning?

**Comment by mitermayer** [comment]
Hi @alanhamlett,

I split the fix in two steps. The first one is to unblock you first by making sure you don't accidentally get you other buffer overwritten.  

I have filled a bug on vim to figure out more details around it (https://github.com/vim/vim/issues/2193) they now have an API for handling this case, however that is only available for vim v8.0.1039+. 

Will create a PR that will conditionally add support for that API for users of vim that has that fix in place.

In the meantime please upgrade your vim to a version over that so that when I do a new vim-prettier release you can leverage from that

**Comment by alanhamlett** [comment]
Oh awesome, thanks!

**Comment by mitermayer** [comment]
@alanhamlett  

I have managed to find a workaround that won't require you to update vim, please feel free to try the new 0.2.2 release version of vim-prettier!

**Pull request merged**
